name: Build SA-MP Mobile Library (.so)

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup Android NDK
      uses: android-actions/setup-android@v3

    - name: Install Specific NDK
      run: |
        sdkmanager --install "ndk;25.1.8937393"

    # Perintah kompilasi menggunakan ndk-build untuk file Android.mk
    - name: Build with NDK
      run: |
        $ANDROID_HOME/ndk/25.1.8937393/ndk-build

    - name: Upload Compiled .so Artifact
      uses: actions/upload-artifact@v4
      with:
        name: samp-cef-libs
        path: libs/
